export const homeObjOne = {
    lightBg : false,
    primary: true, 
    imgStart: "", 
    lightTopLine: false, 
    lightText: true, 
    lightTextDesc: true, 
    buttonLabel: "Get Started", 
    description: "We help business owners increase their revenue. Our team of unique specialist can help you achieve your business goals.", 
    headline: "Lead Generation Specialist for Online Businesses", 
    topLine: "Marketing Agency",
    start: "", 
    img: require("../../images/svg-1.svg"), 
    alt: "Image",
}

export const homeObjTwo = {
    lightBg : false,
    primary: true, 
    imgStart: "", 
    lightTopLine: true, 
    lightText: true, 
    lightTextDesc: true, 
    buttonLabel: "Get Started", 
    description: "We help business owners increase their revenue. Our team of unique specialist can help you achieve your business goals.", 
    headline: "Lead Generation Specialist for Online Businesses", 
    topLine: "Marketing Agency",
    start: "", 
    img: require("../../images/profile.jpg"), 
    alt: "Image",
}

export const homeObjThree = {
    lightBg : false,
    primary: true, 
    imgStart: "", 
    lightTopLine: true, 
    lightText: true, 
    lightTextDesc: true, 
    buttonLabel: "Get Started", 
    description: "We help business owners increase their revenue. Our team of unique specialist can help you achieve your business goals.", 
    headline: "Lead Generation Specialist for Online Businesses", 
    topLine: "Marketing Agency",
    start: "", 
    img: require("../../images/svg-2.svg"), 
    alt: "Image",
}

export const homeObjFour = {
    lightBg : false,
    primary: true, 
    imgStart: "", 
    lightTopLine: true, 
    lightText: true, 
    lightTextDesc: true, 
    buttonLabel: "Get Started", 
    description: "We help business owners increase their revenue. Our team of unique specialist can help you achieve your business goals.", 
    headline: "Lead Generation Specialist for Online Businesses", 
    topLine: "Marketing Agency",
    start: "", 
    img: require("../../images/svg-3.svg"), 
    alt: "Image",
}